#!/bin/bash

if (( $# > 1 )) || [ "$1" != "dev" ] && [ "$1" != "prod" ]; then
    echo "Error: invalid argument. Please specify build environment as an argument."
    echo
    echo "Valid arguments:"
    echo "dev"
    echo "prod"
    exit 1
fi

if [ ! -f "$1.env" ]; then
    echo "Error: file $1.env does not exist in current directory."
    exit 1
fi

TIER=$1 docker-compose build --no-cache && \
TIER=$1 docker-compose -p "ocr-translate-$1" up -d --force-recreate && \
docker image prune --filter label=com.ocr-translate.build=$1 --force